# Importar módulos por página

# Segmentación
from .segmentacion_utils import ls_filtros_generales_empresas, dict_filtros_generales_empresas, ls_filtros_exportadoras, dict_filtros_exportadoras, dict_query_segmentacion, ls_columnas_usuario_segmentacion, query_data_segmentacion, buscar_nits, query_data_razon_social, query_data_nit_individual

# Empresas
from .empresas_utils import ls_filtros_generales_empresas, dict_filtros_generales_empresas, dict_query_empresas, ls_columnas_usuario_empresas, query_data_empresas, calcular_metricas_resumen, crear_resumen_por_tamano, crear_top_exportadoras, crear_empresas_por_tamano

# Destinos
from .destinos_utils import ls_filtros_bienes, dict_filtros_bienes, dict_query_bienes, ls_columnas_usuario_bienes, query_data_bienes, obtener_columnas_valor_y_ultimo_anio, aplicar_formato_columnas, resumen_por_cadena, resumen_por_tamano, resumen_por_pais, resumen_por_pais_tamano, resumen_por_razon_social, conteo_empresas_exportadoras, grafico_barras_multiples, grafico_barras_periodos_seleccionados

# Valor Agregado
from .valor_agregado_utils import ls_filtros_bienes, dict_filtros_bienes, dict_query_bienes, ls_columnas_usuario_bienes, query_data_bienes, aplicar_formato_columnas, resumen_valor_agregado, grafico_barras_multiples, grafico_barras_periodos_seleccionados, top_partidas_por_categoria, top_partidas_por_departamento, conteo_partidas_periodo, renderizar_seccion_valor_agregado, valor_exportado_departamento_long, valor_exportado_departamento_periodo

# Utils
from .utils import load_filtros_generales, load_filtros_exportadoras, load_filtros_bienes, get_filtered_df, transformar_numericas, format_espanol, convert_to_csv, convert_to_excel, descarga_tabla, read_file_content, milify, mostrar_resultado_en_streamlit, load_filtros_departamentos_servicios, load_filtros_departamentos_exportaciones, load_filtros_departamentos_servicios, load_filtros_departamentos_exportaciones, load_filtros_municipios_exportaciones, load_filtros_municipios_socioec

# Mapas - Departamentos
from .mapas_departamentos_utils import ls_filtros_tejido_servicios_departamentos, dict_filtros_tejido_servicios_departamentos, dict_query_tejido_servicios_departamentos, ls_filtros_exportaciones_departamentos, dict_filtros_exportaciones_departamentos, dict_query_exportaciones_departamentos, query_data_tejido_servicios_departamentos, resumen_tejido_servicios_departamentos, crear_mapa_departamentos_servicios, query_data_exportaciones_departamentos, resumen_exportaciones_sectores_departamentos, resumen_empresas_tamano_departamentos, crear_mapa_departamentos_sectores, crear_mapa_departamentos_tamanos

# Mapas - Municipios
from .mapas_municipios_utils import ls_filtros_tejido_municipios, dict_filtros_tejido_municipios, dict_query_tejido_municipios, ls_filtros_socioec_municipios, dict_filtros_socioec_municipios, dict_query_socioec_municipios, query_data_tejido_municipios, resumen_exportaciones_sectores_municipios, crear_mapa_municipios_sectores, resumen_empresas_tamano_municipios, resumen_info_socioeconomica_municipios, crear_mapa_municipios_socioeconomico


# Parámetros generales
from .config import exportaciones_anios_disponibles, servicios_anios_disponibles, negocios_anios_disponibles, oportunidades_anios_disponibles, exportaciones_bienes_servicios_anios_disponibles, periodos_cerrados, periodos_corridos, periodos_cerrados_conteo, periodos_corridos_conteo, periodos_mapa_sector_departamentos, COLS_VARIABLES_TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P_SEGMENTACION_EXPORTACIONES, COLS_VARIABLES_TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P_SEGMENTACION_PC, COLS_VARIABLES_TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P_EMPRESAS, COLS_VARIABLES_USUARIO_COLS_VARIABLES_TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P_EMPRESAS, COLS_VARIABLES_BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P_DESTINOS_VA, COLS_VARIABLES_USUARIOS_COLS_VARIABLES_BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P_DESTINOS_VA, COLS_VARIABLES_DEPARTAMENTOS_EXPORTACIONES, ls_columnas_fob_sectores, COLS_VARIABLES_MUNICIPIOS_EXPORTACIONES, disponibilidad_periodos_corridos_usd, disponibilidad_periodos_corridos_conteo